### ISSUE TITLE
Error: site query ran into an error: please check parameters or stat code...

### ISSUE THREAD

**Issue by shburnet** [joshualerickson/whitewater#3]
I tried the graphing vignette, loaded the necessary packages, and when I attempt the first data retrieval:

#snowmelt
yaak_dv <- ww_dvUSGS('12304500',
                     wy_month = 10)

I receive the error: 

Error: site query ran into an error: please check parameters or stat code...

I also get the same error trying to get the daily values running the #mix code below it too.

**Comment by joshualerickson** [comment]
Hey Sarah, sometimes the server can be fussy. Could you try and run again and see if you get the same error please? I was able to run it on my machine below but maybe there is something going on with your session? Thanks! 

``` r
library(whitewater)
#>  Due to potentially crashing (USGS Water Services) REST services 
#>  parallel processing is kept to  120 requests/min. 
#>  Thank you!

yaak_dv <- ww_dvUSGS('12304500',
                     wy_month = 10)
#> ✔ Yaak River near Troy MT 'daily' was successfully downloaded.
```

<sup>Created on 2023-03-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.0 (2022-04-22 ucrt)
#>  os       Windows 10 x64 (build 19045)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  English_United States.utf8
#>  ctype    English_United States.utf8
#>  tz       America/Denver
#>  date     2023-03-24
#>  pandoc   2.17.1.1 @ C:/Program Files/RStudio/bin/quarto/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package       * version    date (UTC) lib source
#>  assertthat      0.2.1      2019-03-21 [1] CRAN (R 4.2.0)
#>  bit             4.0.4      2020-08-04 [1] CRAN (R 4.2.0)
#>  bit64           4.0.5      2020-08-30 [1] CRAN (R 4.2.0)
#>  class           7.3-20     2022-01-16 [1] CRAN (R 4.2.0)
#>  classInt        0.4-3      2020-04-07 [1] CRAN (R 4.2.0)
#>  cli             3.3.0      2022-04-25 [1] CRAN (R 4.2.0)
#>  codetools       0.2-18     2020-11-04 [1] CRAN (R 4.2.0)
#>  crayon          1.5.1      2022-03-26 [1] CRAN (R 4.2.0)
#>  curl            4.3.2      2021-06-23 [1] CRAN (R 4.2.0)
#>  dataRetrieval   2.7.12     2022-11-24 [1] CRAN (R 4.2.2)
#>  DBI             1.1.2      2021-12-20 [1] CRAN (R 4.2.0)
#>  digest          0.6.29     2021-12-01 [1] CRAN (R 4.2.0)
#>  dplyr           1.0.10     2022-09-01 [1] CRAN (R 4.2.1)
#>  e1071           1.7-9      2021-09-16 [1] CRAN (R 4.2.0)
#>  ellipsis        0.3.2      2021-04-29 [1] CRAN (R 4.2.0)
#>  evaluate        0.15       2022-02-18 [1] CRAN (R 4.2.0)
#>  fansi           1.0.3      2022-03-24 [1] CRAN (R 4.2.0)
#>  fastmap         1.1.0      2021-01-25 [1] CRAN (R 4.2.0)
#>  fs              1.5.2      2021-12-08 [1] CRAN (R 4.2.0)
#>  future          1.25.0     2022-04-24 [1] CRAN (R 4.2.0)
#>  generics        0.1.3      2022-07-05 [1] CRAN (R 4.2.1)
#>  globals         0.14.0     2020-11-22 [1] CRAN (R 4.2.0)
#>  glue            1.6.2      2022-02-24 [1] CRAN (R 4.2.0)
#>  highr           0.9        2021-04-16 [1] CRAN (R 4.2.0)
#>  hms             1.1.1      2021-09-26 [1] CRAN (R 4.2.0)
#>  htmltools       0.5.4      2022-12-07 [1] CRAN (R 4.2.2)
#>  httr            1.4.4      2022-08-17 [1] CRAN (R 4.2.2)
#>  KernSmooth      2.23-20    2021-05-03 [1] CRAN (R 4.2.0)
#>  knitr           1.39       2022-04-26 [1] CRAN (R 4.2.0)
#>  lifecycle       1.0.1      2021-09-24 [1] CRAN (R 4.2.0)
#>  listenv         0.8.0      2019-12-05 [1] CRAN (R 4.2.0)
#>  lubridate       1.8.0      2021-10-07 [1] CRAN (R 4.2.0)
#>  magrittr        2.0.3      2022-03-30 [1] CRAN (R 4.2.0)
#>  parallelly      1.31.1     2022-04-22 [1] CRAN (R 4.2.0)
#>  pillar          1.7.0      2022-02-01 [1] CRAN (R 4.2.0)
#>  pkgconfig       2.0.3      2019-09-22 [1] CRAN (R 4.2.0)
#>  plyr            1.8.7      2022-03-24 [1] CRAN (R 4.2.0)
#>  proxy           0.4-26     2021-06-07 [1] CRAN (R 4.2.0)
#>  purrr           0.3.4      2020-04-17 [1] CRAN (R 4.2.0)
#>  R6              2.5.1      2021-08-19 [1] CRAN (R 4.2.0)
#>  Rcpp            1.0.8.3    2022-03-17 [1] CRAN (R 4.2.0)
#>  readr           2.1.2      2022-01-30 [1] CRAN (R 4.2.0)
#>  reprex          2.0.1      2021-08-05 [1] CRAN (R 4.2.0)
#>  rlang           1.0.6      2022-09-24 [1] CRAN (R 4.2.1)
#>  rmarkdown       2.14       2022-04-25 [1] CRAN (R 4.2.0)
#>  rstudioapi      0.13       2020-11-12 [1] CRAN (R 4.2.0)
#>  sessioninfo     1.2.2      2021-12-06 [1] CRAN (R 4.2.0)
#>  sf              1.0-7      2022-03-07 [1] CRAN (R 4.2.0)
#>  stringi         1.7.6      2021-11-29 [1] CRAN (R 4.2.0)
#>  stringr         1.4.0      2019-02-10 [1] CRAN (R 4.2.0)
#>  tibble          3.1.8      2022-07-22 [1] CRAN (R 4.2.1)
#>  tidyr           1.2.0      2022-02-01 [1] CRAN (R 4.2.0)
#>  tidyselect      1.1.2      2022-02-21 [1] CRAN (R 4.2.0)
#>  tzdb            0.3.0      2022-03-28 [1] CRAN (R 4.2.0)
#>  units           0.8-0      2022-02-05 [1] CRAN (R 4.2.0)
#>  usethis         2.1.5      2021-12-09 [1] CRAN (R 4.2.0)
#>  utf8            1.2.2      2021-07-24 [1] CRAN (R 4.2.0)
#>  vctrs           0.4.1      2022-04-13 [1] CRAN (R 4.2.0)
#>  vroom           1.5.7      2021-11-30 [1] CRAN (R 4.2.0)
#>  whitewater    * 0.1.1.9000 2022-12-13 [1] local
#>  withr           2.5.0      2022-03-03 [1] CRAN (R 4.2.0)
#>  xfun            0.30       2022-03-02 [1] CRAN (R 4.2.0)
#>  xml2            1.3.3      2021-11-30 [1] CRAN (R 4.2.0)
#>  yaml            2.3.5      2022-02-21 [1] CRAN (R 4.2.0)
#> 
#>  [1] C:/R/R-4.2.0/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by shburnet** [comment]
Hi Josh,

Thanks for the response. I just tried and even after restarting my
computer, I am still receiving the same error.

Sarah

**Comment by joshualerickson** [comment]
Interesting, would you mind providing a reprex with your session information attached please? I’m curious if there is something with the package versions in dataRetrieval. Thanks!

**Comment by shburnet** [comment]
I admit I have not used reprex before but this is what I have after
following some directions I found.

library(whitewater)
<http://localhost:18861/session/gaudy-geese_reprex_preview.html#cb1-2>#>
 Due to potentially crashing (USGS Water Services) REST services
<http://localhost:18861/session/gaudy-geese_reprex_preview.html#cb1-3>#>
 parallel processing is kept to  120 requests/min.
<http://localhost:18861/session/gaudy-geese_reprex_preview.html#cb1-4>#>
 Thank you!

library(dplyr) <http://localhost:18861/session/smoky-macaw_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-2>#>
 <http://localhost:18861/session/smoky-macaw_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-3>#>
Attaching package: 'dplyr'
<http://localhost:18861/session/smoky-macaw_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-4>#>
The following objects are masked from 'package:stats':
<http://localhost:18861/session/smoky-macaw_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-5>#>
 <http://localhost:18861/session/smoky-macaw_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-6>#>
    filter, lag
<http://localhost:18861/session/smoky-macaw_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-7>#>
The following objects are masked from 'package:base':
<http://localhost:18861/session/smoky-macaw_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-8>#>
 <http://localhost:18861/session/smoky-macaw_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-9>#>
    intersect, setdiff, setequal, union


library(ggplot2)
<http://localhost:18861/session/piny-loon_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-2>#>
Warning: package 'ggplot2' was built under R version 4.1.3

library(ggfx) <http://localhost:18861/session/pious-rhino_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-2>#>
Warning: package 'ggfx' was built under R version 4.1.3

library(patchwork)
<http://localhost:18861/session/bosky-moa_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-2>#>
Warning: package 'patchwork' was built under R version 4.1.3

library(plotly)
<http://localhost:18861/session/gem-drake_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-2>#>
Warning: package 'plotly' was built under R version 4.1.3
<http://localhost:18861/session/gem-drake_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-3>#>
Loading required package: ggplot2
<http://localhost:18861/session/gem-drake_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-4>#>
Warning: package 'ggplot2' was built under R version 4.1.3
<http://localhost:18861/session/gem-drake_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-5>#>
 <http://localhost:18861/session/gem-drake_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-6>#>
Attaching package: 'plotly'
<http://localhost:18861/session/gem-drake_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-7>#>
The following object is masked from 'package:ggplot2':
<http://localhost:18861/session/gem-drake_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-8>#>
 <http://localhost:18861/session/gem-drake_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-9>#>
    last_plot <http://localhost:18861/session/gem-drake_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-10>#>
The following object is masked from 'package:stats':
<http://localhost:18861/session/gem-drake_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-11>#>
 <http://localhost:18861/session/gem-drake_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-12>#>
    filter <http://localhost:18861/session/gem-drake_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-13>#>
The following object is masked from 'package:graphics':
<http://localhost:18861/session/gem-drake_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-14>#>
 <http://localhost:18861/session/gem-drake_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-15>#>
    layout

yaak_dv <- ww_dvUSGS("12304500", wy_month = 10)
<http://localhost:18861/session/steep-carp_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-2>#>
Error in ww_dvUSGS("12304500", wy_month = 10): could not find function
"ww_dvUSGS"

**Comment by joshualerickson** [comment]
Ok, looks like it's not finding the package. So when you run the code below the same thing happens?

```
library(whitewater)

yaak_dv <- ww_dvUSGS("12304500", wy_month = 10)

```

I'm curious what happens when you call the namespace directly, e.g. `yaak_dv <- whitewater::ww_dvUSGS("12304500", wy_month = 10)`? Does the function 'pop-up'?

**Comment by shburnet** [comment]
The same error pops up as before:

yaak_dv <- whitewater::ww_dvUSGS("12304500", wy_month = 10)
<http://localhost:18861/session/evil-coney_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-2>#>
Error: site query ran into an error: please check parameters or stat
code...

**Comment by joshualerickson** [comment]
If you run `sessionInfo()` could you copy and paste that, please?

**Comment by shburnet** [comment]
> sessionInfo()R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United
States.1252
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] styler_1.9.1     whitewater_0.1.2 reprex_2.0.2     plotly_4.10.1
[5] patchwork_1.1.2  ggfx_1.0.1       ggplot2_3.4.1    dplyr_1.1.1

loaded via a namespace (and not attached):
  [1] fs_1.6.1             sf_1.0-12            usethis_2.1.6
  [4] lubridate_1.9.2      devtools_2.4.5       bit64_4.0.5
  [7] httr_1.4.5           R.cache_0.16.0       tools_4.1.2
 [10] profvis_0.3.7        utf8_1.2.3           R6_2.5.1
 [13] KernSmooth_2.23-20   DBI_1.1.3            lazyeval_0.2.2
 [16] colorspace_2.1-0     urlchecker_1.0.1     withr_2.5.0
 [19] tidyselect_1.2.0     prettyunits_1.1.1    processx_3.8.0
 [22] bit_4.0.5            curl_5.0.0           compiler_4.1.2
 [25] textshaping_0.3.6    cli_3.6.1            xml2_1.3.3
 [28] dataRetrieval_2.7.12 scales_1.2.1         classInt_0.4-9
 [31] readr_2.1.4          callr_3.7.3          proxy_0.4-27
 [34] systemfonts_1.0.4    stringr_1.5.0        digest_0.6.31
 [37] R.utils_2.12.2       rmarkdown_2.20       pkgconfig_2.0.3
 [40] htmltools_0.5.4      parallelly_1.35.0    sessioninfo_1.2.2
 [43] fastmap_1.1.1        htmlwidgets_1.6.2    rlang_1.1.0
 [46] rstudioapi_0.14      shiny_1.7.4          generics_0.1.3
 [49] jsonlite_1.8.4       vroom_1.6.1          R.oo_1.25.0
 [52] magrittr_2.0.3       Rcpp_1.0.10          munsell_0.5.0
 [55] fansi_1.0.4          clipr_0.8.0          R.methodsS3_1.8.2
 [58] lifecycle_1.0.3      yaml_2.3.7           stringi_1.7.12
 [61] pkgbuild_1.4.0       plyr_1.8.8           grid_4.1.2
 [64] parallel_4.1.2       listenv_0.9.0        promises_1.2.0.1
 [67] crayon_1.5.2         miniUI_0.1.1.1       hms_1.1.3
 [70] magick_2.7.4         knitr_1.42           ps_1.7.3
 [73] pillar_1.9.0         codetools_0.2-18     pkgload_1.3.2
 [76] glue_1.6.2           evaluate_0.20        data.table_1.14.8
 [79] remotes_2.4.2        vctrs_0.6.1          tzdb_0.3.0
 [82] httpuv_1.6.9         gtable_0.3.3         purrr_1.0.1
 [85] tidyr_1.3.0          future_1.32.0        cachem_1.0.7
 [88] xfun_0.37            mime_0.12            xtable_1.8-4
 [91] e1071_1.7-13         later_1.3.0          ragg_1.2.5
 [94] class_7.3-19         viridisLite_0.4.1    tibble_3.2.1
 [97] memoise_2.0.1        units_0.8-1          timechange_0.2.0
[100] globals_0.16.2       ellipsis_0.3.2

**Comment by joshualerickson** [comment]
Ok thanks! Sorry for having run through all this but could you try and download the station directly using dataRetrieval? Just trying to isolate why it's not letting you download....

```
yaak_dv <- dataRetrieval::readNWISdv('12304500', parameterCd = '00060')
```

**Comment by shburnet** [comment]
No problem! And I was able to download the station data using that line of
code!

**Comment by joshualerickson** [comment]
That's really interesting because that is essentially what whitewater calls behind the scenes. I wonder what happens when you do this below? Thanks.

**Try this first**
```

site_id <- data.frame(sites = '12304500')

usgs_raw_dv <- site_id %>%
  split(.$sites) %>%
  purrr::map(purrr::safely(~whitewater:::prepping_USGSdv(.$sites,
                                            '00060',
                                            '',
                                            '',
                                            '00003',
                                            TRUE,
                                            delay = 0
  ))) %>%
  purrr::keep(~length(.) != 0) %>%
  purrr::map(~.x[['result']]) %>%
  plyr::rbind.fill()


```
**Just in case if above doesn't work**
```
gage_data_test <- dataRetrieval::readNWISdv(siteNumbers = '12304500',
                        parameterCd = '00060',
                        startDate = '',
                        endDate = '',
                        statCd = '00003') %>%
  dataRetrieval::renameNWISColumns(p70290 = "Chloride")

gage_info_test <- dplyr::tibble(
  site_no = '12304500',
  drainage_area = dataRetrieval::readNWISsite(site_no) %>% dplyr::select(drain_area_va) %>% as.numeric(),
  Station = dataRetrieval::readNWISsite(site_no) %>%  dplyr::select(station_nm) %>% as.character(),
  lat = dataRetrieval::readNWISsite(site_no) %>%  dplyr::select(dec_lat_va) %>% as.numeric(),
  long = dataRetrieval::readNWISsite(site_no) %>%  dplyr::select(dec_long_va) %>% as.numeric(),
  altitude = dataRetrieval::readNWISsite(site_no) %>%  dplyr::select(alt_va) %>% as.numeric()
)


```

**Comment by shburnet** [comment]
The first set of code didn't work "values" for usgs_raw_dv" are listed as
NULL
Using reprex, this pops up but I have dplyr loaded

usgs_raw_dv <- site_id %>% split(.$sites) %>%
purrr::map(purrr::safely(~whitewater:::prepping_USGSdv(.$sites,
<http://localhost:18861/session/fresh-hare_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-2>
   "00060", "", "", "00003", TRUE, delay = 0))) %>%
purrr::keep(~length(.) !=
<http://localhost:18861/session/fresh-hare_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-3>
   0) %>% purrr::map(~.x[["result"]]) %>% plyr::rbind.fill()
<http://localhost:18861/session/fresh-hare_reprex_preview.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A23475#cb1-4>#>
Error in site_id %>% split(.$sites) %>%
purrr::map(purrr::safely(~whitewater:::prepping_USGSdv(.$sites, :
could not find function "%>%"


The second set of code works and produces data for both gage_data_test and
gage_info_test.

If it's easier, we could troubleshoot over email or zoom too!

**Comment by joshualerickson** [comment]
Alright, I think we isolated it! It was in the recent dplyr update in the `slice()` function. They removed an argument that I had from an older version. 

If you can restart your session then `devtools::install_github('joshualerickson/whitewater')`; restart again and then rerun the example code from the vignette. This should work 🤞.

**Comment by shburnet** [comment]
It did! And I was able to get the rest of the vignette running! Thank you
so much for working through that!

**Comment by joshualerickson** [comment]
No problem, glad it worked! Thanks for submitting and working through that! Very sneaky bug...
